/* emoji-data — hand-authored static dataset for the emoji picker
 * and the inline ":" trigger. A file, not a dependency.
 *
 * Names use the shortcode convention (lowercase, hyphens). Keywords
 * carry synonyms so search finds things by intent. Underscores in a
 * query are treated as hyphens so `:thumbs_up:` still finds it.
 */

export type EmojiCategory =
  | "people"
  | "nature"
  | "food"
  | "activity"
  | "travel"
  | "objects"
  | "symbols";

export type Emoji = {
  char: string;
  name: string;
  keywords: string[];
  category: EmojiCategory;
};

const P = (char: string, name: string, keywords: string[] = []): Emoji => ({
  char, name, keywords, category: "people",
});
const N = (char: string, name: string, keywords: string[] = []): Emoji => ({
  char, name, keywords, category: "nature",
});
const F = (char: string, name: string, keywords: string[] = []): Emoji => ({
  char, name, keywords, category: "food",
});
const A = (char: string, name: string, keywords: string[] = []): Emoji => ({
  char, name, keywords, category: "activity",
});
const T = (char: string, name: string, keywords: string[] = []): Emoji => ({
  char, name, keywords, category: "travel",
});
const O = (char: string, name: string, keywords: string[] = []): Emoji => ({
  char, name, keywords, category: "objects",
});
const S = (char: string, name: string, keywords: string[] = []): Emoji => ({
  char, name, keywords, category: "symbols",
});

export const EMOJI: readonly Emoji[] = [
  // ─── People — faces ───────────────────────────────────────────
  P("😀", "grinning", ["happy", "smile"]),
  P("😃", "smiley", ["happy", "smile"]),
  P("😄", "smile", ["happy", "grin"]),
  P("😁", "beaming", ["happy", "grin"]),
  P("😆", "laughing", ["haha", "lol"]),
  P("😅", "sweat-smile", ["nervous", "phew"]),
  P("🤣", "rofl", ["laugh", "lol", "funny"]),
  P("😂", "joy", ["tears", "laugh", "cry-laugh"]),
  P("🙂", "slight-smile", ["ok"]),
  P("🙃", "upside-down", ["silly", "ironic"]),
  P("😉", "wink", ["flirt"]),
  P("😊", "blush", ["happy", "smile"]),
  P("😇", "innocent", ["angel", "halo"]),
  P("🥰", "smiling-with-hearts", ["love"]),
  P("😍", "heart-eyes", ["love"]),
  P("🤩", "star-struck", ["excited", "wow"]),
  P("😘", "kiss", ["love"]),
  P("😗", "kissing", ["kiss"]),
  P("😚", "kissing-closed-eyes", ["kiss"]),
  P("😋", "yum", ["tasty", "delicious"]),
  P("😛", "tongue", ["silly"]),
  P("😜", "tongue-wink", ["silly", "playful"]),
  P("🤪", "zany", ["silly", "crazy"]),
  P("🤨", "raised-eyebrow", ["suspicious", "skeptical"]),
  P("🧐", "monocle", ["examine", "inspect"]),
  P("🤓", "nerd", ["glasses", "smart"]),
  P("😎", "sunglasses", ["cool"]),
  P("🥸", "disguise", ["incognito"]),
  P("🤗", "hug", ["hugs"]),
  P("🤔", "thinking", ["hmm", "consider"]),
  P("🤫", "shush", ["quiet", "secret"]),
  P("🤥", "lying", ["pinocchio"]),
  P("😐", "neutral-face", ["meh"]),
  P("😑", "expressionless", ["blank"]),
  P("😶", "no-mouth", ["silent"]),
  P("😏", "smirk", ["smug"]),
  P("😒", "unamused", ["annoyed"]),
  P("🙄", "eye-roll", ["annoyed"]),
  P("😬", "grimace", ["awkward"]),
  P("🤥", "liar", ["lie"]),
  P("😔", "pensive", ["sad"]),
  P("😕", "confused", ["unsure"]),
  P("🙁", "slight-frown", ["sad"]),
  P("☹️", "frown", ["sad"]),
  P("😣", "persevere", ["struggle"]),
  P("😖", "confounded", ["frustrated"]),
  P("😫", "tired", ["exhausted"]),
  P("😩", "weary", ["exhausted"]),
  P("🥺", "pleading", ["puppy-eyes", "please"]),
  P("😢", "cry", ["sad", "tear"]),
  P("😭", "sob", ["crying", "sad"]),
  P("😤", "triumph", ["huff"]),
  P("😠", "angry", ["mad"]),
  P("😡", "rage", ["mad", "angry"]),
  P("🤬", "cursing", ["swearing"]),
  P("🤯", "mind-blown", ["shocked", "wow"]),
  P("😳", "flushed", ["blush", "embarrassed"]),
  P("🥵", "hot", ["heat", "sweat"]),
  P("🥶", "cold", ["freezing"]),
  P("😱", "scream", ["shocked", "fear"]),
  P("😨", "fearful", ["scared"]),
  P("😰", "anxious", ["worried"]),
  P("😥", "sad-relieved", ["disappointed"]),
  P("😓", "downcast", ["sweat", "sad"]),
  P("🤝", "handshake", ["deal", "agreement", "partner"]),
  P("🙏", "pray", ["thanks", "please"]),
  P("💪", "muscle", ["strong", "flex"]),
  // gestures
  P("👍", "thumbs-up", ["yes", "approve", "like", "ok"]),
  P("👎", "thumbs-down", ["no", "disapprove", "dislike"]),
  P("👌", "ok-hand", ["okay", "good"]),
  P("✌️", "victory", ["peace"]),
  P("🤞", "fingers-crossed", ["luck", "hope"]),
  P("🤟", "love-you", ["ily"]),
  P("🤘", "rock-on", ["metal"]),
  P("🤙", "call-me", ["shaka"]),
  P("👈", "point-left", ["left"]),
  P("👉", "point-right", ["right"]),
  P("👆", "point-up", ["up"]),
  P("👇", "point-down", ["down"]),
  P("☝️", "index-up", ["one", "point"]),
  P("👋", "wave", ["hello", "hi", "bye"]),
  P("🤚", "raised-back-of-hand", ["stop"]),
  P("✋", "raised-hand", ["stop", "high-five"]),
  P("🖐️", "hand", ["five"]),
  P("🖖", "vulcan", ["spock"]),
  P("👏", "clap", ["applause", "bravo"]),
  P("🙌", "raised-hands", ["celebrate", "praise"]),
  P("👐", "open-hands", ["welcome"]),
  P("🤲", "palms-up", ["please", "offer"]),
  P("🫶", "heart-hands", ["love"]),
  P("✍️", "writing-hand", ["write", "author"]),
  // people & roles
  P("🧑", "person", ["individual"]),
  P("👤", "silhouette", ["profile", "user"]),
  P("👥", "silhouettes", ["users", "team"]),
  P("👶", "baby", ["infant"]),
  P("🧒", "child", ["kid"]),
  P("👦", "boy", ["child"]),
  P("👧", "girl", ["child"]),
  P("🧓", "older", ["senior"]),
  P("👨", "man", []),
  P("👩", "woman", []),
  P("👨‍💼", "office-worker-man", ["business"]),
  P("👩‍💼", "office-worker-woman", ["business"]),
  P("🧑‍💻", "technologist", ["developer", "engineer", "code"]),
  P("🧑‍🔬", "scientist", ["research", "lab"]),
  P("🧑‍🏫", "teacher", ["educator"]),
  P("👨‍⚕️", "doctor-man", ["medic", "health"]),
  P("👩‍⚕️", "doctor-woman", ["medic", "health"]),
  P("🕵️", "detective", ["spy", "sleuth"]),

  // ─── Nature — animals, plants, weather ────────────────────────
  N("🐶", "dog-face", ["puppy", "pet"]),
  N("🐱", "cat-face", ["kitten", "pet"]),
  N("🐭", "mouse-face", []),
  N("🐹", "hamster", []),
  N("🐰", "rabbit-face", ["bunny"]),
  N("🦊", "fox", []),
  N("🐻", "bear", []),
  N("🐼", "panda", []),
  N("🐨", "koala", []),
  N("🐯", "tiger-face", []),
  N("🦁", "lion", []),
  N("🐮", "cow-face", []),
  N("🐷", "pig-face", []),
  N("🐸", "frog", []),
  N("🐵", "monkey-face", []),
  N("🐔", "chicken", []),
  N("🐧", "penguin", []),
  N("🐦", "bird", []),
  N("🐤", "chick", []),
  N("🦆", "duck", []),
  N("🦅", "eagle", []),
  N("🦉", "owl", ["wisdom"]),
  N("🐺", "wolf", []),
  N("🐗", "boar", ["pig"]),
  N("🐴", "horse-face", []),
  N("🦄", "unicorn", ["magic"]),
  N("🐝", "bee", ["honey"]),
  N("🐛", "bug", []),
  N("🦋", "butterfly", []),
  N("🐌", "snail", ["slow"]),
  N("🐞", "ladybug", []),
  N("🐜", "ant", []),
  N("🕷️", "spider", []),
  N("🦂", "scorpion", []),
  N("🐢", "turtle", ["slow"]),
  N("🐍", "snake", []),
  N("🦎", "lizard", ["gecko"]),
  N("🐙", "octopus", []),
  N("🦑", "squid", []),
  N("🦐", "shrimp", []),
  N("🦀", "crab", []),
  N("🐟", "fish", []),
  N("🐬", "dolphin", []),
  N("🐳", "whale", []),
  N("🦈", "shark", []),
  N("🐊", "crocodile", []),
  N("🐘", "elephant", []),
  N("🦏", "rhino", []),
  N("🦒", "giraffe", []),
  N("🐪", "camel", []),
  N("🦘", "kangaroo", []),
  N("🌳", "tree", ["nature"]),
  N("🌲", "evergreen", ["pine", "fir"]),
  N("🌴", "palm-tree", ["tropical"]),
  N("🌵", "cactus", ["desert"]),
  N("🌿", "herb", ["plant"]),
  N("🍀", "clover", ["luck", "four-leaf"]),
  N("🍁", "maple-leaf", ["autumn"]),
  N("🍂", "fallen-leaves", ["autumn"]),
  N("🌱", "seedling", ["grow", "sprout", "plant"]),
  N("🌷", "tulip", ["flower"]),
  N("🌹", "rose", ["flower", "love"]),
  N("🌸", "cherry-blossom", ["sakura"]),
  N("🌻", "sunflower", []),
  N("🌼", "blossom", ["flower"]),
  N("💐", "bouquet", ["flowers"]),
  N("☀️", "sun", ["sunny", "day"]),
  N("🌤️", "sun-behind-cloud", []),
  N("⛅", "partly-cloudy", []),
  N("☁️", "cloud", ["cloudy"]),
  N("🌧️", "rain-cloud", ["rain"]),
  N("⛈️", "thunderstorm", ["storm"]),
  N("🌩️", "lightning-cloud", ["thunder"]),
  N("❄️", "snowflake", ["snow", "cold", "winter"]),
  N("☃️", "snowman", ["winter"]),
  N("🌈", "rainbow", ["pride"]),
  N("🌊", "wave", ["ocean", "water"]),
  N("🔥", "fire", ["hot", "flame", "lit"]),
  N("💧", "droplet", ["water", "drop"]),

  // ─── Food ─────────────────────────────────────────────────────
  F("🍏", "green-apple", []),
  F("🍎", "red-apple", []),
  F("🍐", "pear", []),
  F("🍊", "orange", ["tangerine"]),
  F("🍋", "lemon", []),
  F("🍌", "banana", []),
  F("🍉", "watermelon", []),
  F("🍇", "grapes", []),
  F("🍓", "strawberry", []),
  F("🫐", "blueberries", []),
  F("🍈", "melon", []),
  F("🍒", "cherries", []),
  F("🍑", "peach", []),
  F("🥭", "mango", []),
  F("🍍", "pineapple", []),
  F("🥥", "coconut", []),
  F("🥝", "kiwi", []),
  F("🍅", "tomato", []),
  F("🥑", "avocado", []),
  F("🥦", "broccoli", []),
  F("🥕", "carrot", []),
  F("🌽", "corn", []),
  F("🌶️", "chili-pepper", ["spicy", "hot"]),
  F("🥔", "potato", []),
  F("🧅", "onion", []),
  F("🧄", "garlic", []),
  F("🍄", "mushroom", []),
  F("🍞", "bread", ["loaf"]),
  F("🥐", "croissant", []),
  F("🥖", "baguette", []),
  F("🧀", "cheese", []),
  F("🥚", "egg", []),
  F("🍳", "cooking", ["fried-egg", "pan"]),
  F("🥞", "pancakes", []),
  F("🧇", "waffle", []),
  F("🥓", "bacon", []),
  F("🥩", "steak", ["meat"]),
  F("🍗", "poultry", ["chicken-leg"]),
  F("🍔", "burger", ["hamburger"]),
  F("🍟", "fries", ["chips"]),
  F("🍕", "pizza", []),
  F("🌭", "hot-dog", []),
  F("🥪", "sandwich", []),
  F("🌮", "taco", []),
  F("🌯", "burrito", []),
  F("🥗", "salad", []),
  F("🍝", "spaghetti", ["pasta"]),
  F("🍜", "ramen", ["noodles"]),
  F("🍣", "sushi", []),
  F("🍱", "bento", []),
  F("🍚", "rice", []),
  F("🍤", "shrimp-tempura", []),
  F("🍦", "soft-ice-cream", []),
  F("🍨", "ice-cream", []),
  F("🍩", "doughnut", ["donut"]),
  F("🍪", "cookie", []),
  F("🎂", "birthday-cake", ["birthday"]),
  F("🍰", "cake", []),
  F("🧁", "cupcake", []),
  F("🍫", "chocolate", []),
  F("🍬", "candy", []),
  F("🍯", "honey", []),
  F("☕", "coffee", ["latte", "espresso"]),
  F("🍵", "tea", []),
  F("🥛", "milk", []),
  F("🍺", "beer", []),
  F("🍻", "cheers", ["beers", "clink"]),
  F("🍷", "wine", []),
  F("🥂", "champagne-clink", ["toast", "celebrate"]),
  F("🍸", "cocktail", []),
  F("🥃", "whisky", ["scotch"]),
  F("🧉", "mate", []),
  F("🧊", "ice", ["cube"]),
  F("🍽️", "plate-cutlery", ["meal", "dinner"]),

  // ─── Activity ────────────────────────────────────────────────
  A("⚽", "soccer", ["football"]),
  A("🏀", "basketball", []),
  A("🏈", "football", ["american"]),
  A("⚾", "baseball", []),
  A("🎾", "tennis", []),
  A("🏐", "volleyball", []),
  A("🏉", "rugby", []),
  A("🎱", "billiards", ["pool"]),
  A("🏓", "ping-pong", ["table-tennis"]),
  A("🏸", "badminton", []),
  A("🥅", "goal", []),
  A("⛳", "golf", []),
  A("🏒", "hockey", []),
  A("🥊", "boxing", ["gloves"]),
  A("🥋", "martial-arts", ["karate", "judo"]),
  A("🎽", "running-shirt", []),
  A("🛹", "skateboard", []),
  A("⛸️", "skate", ["ice-skating"]),
  A("🎿", "skis", ["skiing"]),
  A("🏂", "snowboard", []),
  A("🏄", "surfing", []),
  A("🏊", "swimming", []),
  A("🚴", "cycling", ["bike"]),
  A("🏃", "runner", ["running"]),
  A("🚶", "walking", []),
  A("🧗", "climbing", []),
  A("🏆", "trophy", ["winner", "award"]),
  A("🥇", "gold-medal", ["first"]),
  A("🥈", "silver-medal", ["second"]),
  A("🥉", "bronze-medal", ["third"]),
  A("🏅", "medal", []),
  A("🎖️", "military-medal", ["honor"]),
  A("🎗️", "reminder-ribbon", []),
  A("🎟️", "ticket", ["admission"]),
  A("🎫", "ticket-stub", []),
  A("🎪", "circus", ["tent"]),
  A("🎭", "performing-arts", ["theater", "masks"]),
  A("🎨", "artist-palette", ["art", "paint", "design"]),
  A("🎬", "clapper", ["movie", "film"]),
  A("🎤", "microphone", ["mic", "sing"]),
  A("🎧", "headphones", ["music", "listen"]),
  A("🎵", "musical-note", ["music"]),
  A("🎶", "musical-notes", ["music"]),
  A("🎹", "piano", ["keyboard"]),
  A("🥁", "drum", []),
  A("🎸", "guitar", []),
  A("🎺", "trumpet", []),
  A("🎷", "saxophone", []),
  A("🎻", "violin", []),
  A("🎲", "die", ["dice", "random"]),
  A("♟️", "chess-pawn", ["chess"]),
  A("🧩", "puzzle", ["jigsaw", "piece"]),
  A("🎯", "dart", ["target", "goal", "aim", "bullseye"]),
  A("🎳", "bowling", []),
  A("🎮", "video-game", ["gaming", "controller"]),
  A("🕹️", "joystick", []),
  A("🎉", "party-popper", ["celebrate", "party", "yay"]),
  A("🎊", "confetti", ["celebrate"]),
  A("🎈", "balloon", ["party"]),
  A("🎁", "gift", ["present"]),
  A("🎀", "ribbon", ["bow"]),

  // ─── Travel & places ─────────────────────────────────────────
  T("🚗", "car", ["auto"]),
  T("🚕", "taxi", ["cab"]),
  T("🚙", "suv", []),
  T("🚌", "bus", []),
  T("🚎", "trolleybus", []),
  T("🏎️", "race-car", []),
  T("🚓", "police-car", []),
  T("🚑", "ambulance", []),
  T("🚒", "fire-engine", []),
  T("🚚", "truck", ["delivery"]),
  T("🚛", "articulated-lorry", ["truck"]),
  T("🚜", "tractor", []),
  T("🏍️", "motorcycle", ["motorbike"]),
  T("🛵", "scooter", ["moped"]),
  T("🚲", "bicycle", ["bike"]),
  T("🛴", "kick-scooter", []),
  T("🚂", "locomotive", ["train"]),
  T("🚆", "train", []),
  T("🚇", "metro", ["subway"]),
  T("🚊", "tram", []),
  T("🚝", "monorail", []),
  T("🚄", "high-speed-train", ["shinkansen"]),
  T("✈️", "airplane", ["plane", "flight"]),
  T("🛫", "takeoff", []),
  T("🛬", "landing", []),
  T("🚁", "helicopter", []),
  T("🚀", "rocket", ["launch", "ship"]),
  T("🛸", "ufo", ["saucer"]),
  T("⛵", "sailboat", []),
  T("🚤", "speedboat", []),
  T("🛥️", "motor-boat", []),
  T("🚢", "ship", []),
  T("⚓", "anchor", ["boat"]),
  T("🗺", "world-map", ["map"]),
  T("🧭", "compass", ["navigation", "direction"]),
  T("🗽", "statue-of-liberty", []),
  T("🗼", "tokyo-tower", []),
  T("🏰", "castle", []),
  T("🏯", "japanese-castle", []),
  T("🏟️", "stadium", []),
  T("🎡", "ferris-wheel", []),
  T("🎢", "roller-coaster", []),
  T("🎠", "carousel-horse", []),
  T("🏖️", "beach", ["umbrella"]),
  T("🏝️", "desert-island", ["island"]),
  T("⛰️", "mountain", []),
  T("🏔️", "snow-mountain", []),
  T("🌋", "volcano", []),
  T("🏕️", "camping", ["tent"]),
  T("🏠", "house", ["home"]),
  T("🏡", "home", ["house", "garden"]),
  T("🏢", "office-building", ["office"]),
  T("🏬", "department-store", []),
  T("🏥", "hospital", []),
  T("🏦", "bank", []),
  T("🏛", "classical-building", ["museum"]),
  T("🏫", "school", []),
  T("⛪", "church", []),
  T("🕌", "mosque", []),
  T("🕍", "synagogue", []),
  T("🗿", "moai", ["statue"]),

  // ─── Objects — office, tech, tools, documents ────────────────
  O("📄", "page", ["document", "sheet"]),
  O("📃", "page-with-curl", []),
  O("📑", "bookmark-tabs", []),
  O("📊", "bar-chart", ["chart", "graph", "data"]),
  O("📈", "chart-up", ["trend", "growth"]),
  O("📉", "chart-down", ["decline"]),
  O("📇", "card-index", ["contacts"]),
  O("🗃", "card-file-box", ["archive"]),
  O("🗄", "file-cabinet", []),
  O("🗂", "dividers", ["folders", "organize"]),
  O("📁", "folder", ["directory"]),
  O("📂", "open-folder", []),
  O("📋", "clipboard", []),
  O("📌", "pushpin", ["pin"]),
  O("📍", "round-pushpin", ["location", "here"]),
  O("📎", "paperclip", ["attach"]),
  O("🖇", "linked-paperclips", ["link"]),
  O("📏", "ruler", ["measure"]),
  O("📐", "triangular-ruler", []),
  O("✂️", "scissors", ["cut"]),
  O("🗒", "notepad", ["spiral"]),
  O("📓", "notebook", ["notes"]),
  O("📔", "notebook-with-cover", []),
  O("📕", "closed-book", []),
  O("📗", "green-book", []),
  O("📘", "blue-book", []),
  O("📙", "orange-book", []),
  O("📚", "books", ["library", "read"]),
  O("📖", "open-book", ["read"]),
  O("🔖", "bookmark", ["save"]),
  O("🏷", "label", ["tag"]),
  O("💼", "briefcase", ["work", "business"]),
  O("📝", "memo", ["write", "note", "edit"]),
  O("✏️", "pencil", ["write", "edit"]),
  O("🖊", "pen", ["write"]),
  O("🖋", "fountain-pen", ["write"]),
  O("🖌", "paintbrush", ["paint"]),
  O("🖍", "crayon", []),
  O("📮", "postbox", ["mail"]),
  O("📧", "email", ["mail", "envelope"]),
  O("📨", "incoming-mail", []),
  O("📩", "envelope-with-arrow", ["send"]),
  O("📤", "outbox", ["send"]),
  O("📥", "inbox", ["receive"]),
  O("📦", "package", ["box", "delivery"]),
  O("📫", "mailbox", []),
  O("📞", "phone", ["telephone", "call"]),
  O("📱", "mobile", ["phone", "smartphone"]),
  O("💻", "laptop", ["computer"]),
  O("🖥", "desktop", ["computer", "monitor"]),
  O("🖨", "printer", ["print"]),
  O("⌨️", "keyboard", ["type"]),
  O("🖱", "mouse-device", ["cursor"]),
  O("💾", "floppy", ["save", "disk"]),
  O("💿", "cd", ["disc"]),
  O("📀", "dvd", []),
  O("📷", "camera", ["photo"]),
  O("📸", "camera-flash", ["photo"]),
  O("📹", "video-camera", []),
  O("🎥", "movie-camera", []),
  O("📺", "tv", ["television"]),
  O("📻", "radio", []),
  O("🕰", "mantelpiece-clock", ["time"]),
  O("⏰", "alarm", ["clock", "wake"]),
  O("⏱", "stopwatch", ["timer"]),
  O("⌛", "hourglass", ["time", "waiting"]),
  O("💡", "bulb", ["idea", "light"]),
  O("🔦", "flashlight", ["torch"]),
  O("🔧", "wrench", ["tool", "fix", "settings"]),
  O("🔨", "hammer", ["tool", "build"]),
  O("🛠", "hammer-and-wrench", ["tools", "settings", "fix"]),
  O("⚙️", "gear", ["settings", "cog"]),
  O("🧰", "toolbox", ["tools"]),
  O("🔩", "bolt", ["screw"]),
  O("🔒", "lock", ["secure", "private"]),
  O("🔓", "unlock", ["open"]),
  O("🔑", "key", ["access", "unlock"]),
  O("🗝", "old-key", []),
  O("🔍", "magnifying-glass", ["search", "zoom", "find"]),
  O("🔎", "magnifier-right", ["search"]),
  O("💰", "money-bag", ["cash"]),
  O("💵", "dollar", ["cash", "money"]),
  O("💳", "credit-card", ["pay"]),
  O("🧾", "receipt", ["invoice"]),
  O("📅", "calendar", ["date", "schedule"]),
  O("📆", "tear-off-calendar", ["schedule"]),
  O("🗓", "spiral-calendar", []),
  O("🧠", "brain", ["mind", "smart", "idea"]),
  O("🧪", "test-tube", ["chemistry", "experiment"]),
  O("🧬", "dna", ["genetics"]),
  O("🔬", "microscope", ["science"]),
  O("🔭", "telescope", ["astronomy"]),

  // ─── Symbols — arrows, marks, status ─────────────────────────
  S("❤️", "red-heart", ["love"]),
  S("🧡", "orange-heart", []),
  S("💛", "yellow-heart", []),
  S("💚", "green-heart", []),
  S("💙", "blue-heart", []),
  S("💜", "purple-heart", []),
  S("🖤", "black-heart", []),
  S("🤍", "white-heart", []),
  S("💔", "broken-heart", []),
  S("❣️", "heart-exclamation", []),
  S("💕", "two-hearts", []),
  S("💖", "sparkling-heart", []),
  S("💗", "growing-heart", []),
  S("💘", "heart-with-arrow", []),
  S("✨", "sparkles", ["magic", "shine"]),
  S("⭐", "star", ["favourite"]),
  S("🌟", "glowing-star", ["shine"]),
  S("💫", "dizzy", ["star"]),
  S("⚡", "zap", ["lightning", "bolt", "fast"]),
  S("💥", "boom", ["explosion", "collision"]),
  S("💯", "hundred", ["perfect", "score", "keep-it-100"]),
  S("✅", "white-check-mark", ["yes", "done", "check", "confirm"]),
  S("✔️", "check-mark", ["done", "yes"]),
  S("☑️", "check-box", ["done"]),
  S("❌", "cross-mark", ["no", "cancel", "wrong"]),
  S("❎", "cross-mark-button", ["no"]),
  S("⭕", "circle", ["ok", "correct"]),
  S("🚫", "prohibited", ["no", "banned", "forbidden"]),
  S("⛔", "no-entry", ["stop"]),
  S("⚠️", "warning", ["caution", "alert", "danger"]),
  S("❗", "exclamation", ["important"]),
  S("❓", "question", ["huh"]),
  S("❕", "grey-exclamation", []),
  S("❔", "grey-question", []),
  S("‼️", "double-exclamation", ["important"]),
  S("⁉️", "interrobang", []),
  S("🔴", "red-circle", ["stop", "urgent"]),
  S("🟠", "orange-circle", []),
  S("🟡", "yellow-circle", ["caution"]),
  S("🟢", "green-circle", ["go", "ok"]),
  S("🔵", "blue-circle", []),
  S("🟣", "purple-circle", []),
  S("⚫", "black-circle", []),
  S("⚪", "white-circle", []),
  S("🟥", "red-square", []),
  S("🟧", "orange-square", []),
  S("🟨", "yellow-square", []),
  S("🟩", "green-square", []),
  S("🟦", "blue-square", []),
  S("🟪", "purple-square", []),
  S("⬛", "black-square", []),
  S("⬜", "white-square", []),
  S("🔺", "red-triangle-up", []),
  S("🔻", "red-triangle-down", []),
  S("🔶", "large-orange-diamond", []),
  S("🔷", "large-blue-diamond", []),
  S("⬆️", "arrow-up", ["up"]),
  S("⬇️", "arrow-down", ["down"]),
  S("⬅️", "arrow-left", ["left"]),
  S("➡️", "arrow-right", ["right"]),
  S("↗️", "arrow-up-right", []),
  S("↘️", "arrow-down-right", []),
  S("↙️", "arrow-down-left", []),
  S("↖️", "arrow-up-left", []),
  S("↕️", "arrow-up-down", []),
  S("↔️", "arrow-left-right", []),
  S("🔀", "shuffle", ["random"]),
  S("🔁", "repeat", ["loop"]),
  S("🔂", "repeat-one", []),
  S("▶️", "play", ["start"]),
  S("⏸", "pause", []),
  S("⏹", "stop-button", []),
  S("⏺", "record", []),
  S("⏭", "next-track", ["skip"]),
  S("⏮", "previous-track", []),
  S("⏩", "fast-forward", []),
  S("⏪", "rewind", []),
  S("🆕", "new", []),
  S("🆗", "ok-button", []),
  S("🆒", "cool-button", []),
  S("🆙", "up-button", []),
  S("🆓", "free-button", []),
  S("🔔", "bell", ["notify", "alert"]),
  S("🔕", "bell-muted", ["silent"]),
  S("♻️", "recycle", ["eco"]),
  S("✳️", "eight-spoked-asterisk", []),
  S("✴️", "eight-pointed-star", []),
  S("💤", "zzz", ["sleep"]),
];

/* Normalise a query: lowercase, trim, and treat underscores as
 * hyphens so `:thumbs_up:` finds `thumbs-up`. */
function normQuery(q: string): string {
  return q.toLowerCase().trim().replace(/_/g, "-");
}

/* Ranking:
 *   0 — name starts with query (best)
 *   1 — keyword equals or starts with query
 *   2 — name contains query
 *   3 — keyword contains query
 * Ties broken by natural array order.
 */
function score(e: Emoji, q: string): number | null {
  const name = e.name;
  if (name.startsWith(q)) return 0;
  for (const k of e.keywords) {
    if (k === q || k.startsWith(q)) return 1;
  }
  if (name.includes(q)) return 2;
  for (const k of e.keywords) {
    if (k.includes(q)) return 3;
  }
  return null;
}

export function searchEmoji(query: string, limit = 40): Emoji[] {
  const q = normQuery(query);
  if (!q) return []; // empty query returns nothing; the picker handles the section view itself
  const scored: Array<{ e: Emoji; s: number; i: number }> = [];
  for (let i = 0; i < EMOJI.length; i++) {
    const s = score(EMOJI[i], q);
    if (s !== null) scored.push({ e: EMOJI[i], s, i });
  }
  scored.sort((a, b) => (a.s - b.s) || (a.i - b.i));
  return scored.slice(0, limit).map((x) => x.e);
}

export const CATEGORY_ORDER: readonly EmojiCategory[] = [
  "people", "nature", "food", "activity", "travel", "objects", "symbols",
];

export const CATEGORY_LABEL: Record<EmojiCategory, string> = {
  people: "People",
  nature: "Nature",
  food: "Food & Drink",
  activity: "Activity",
  travel: "Travel & Places",
  objects: "Objects",
  symbols: "Symbols",
};

/* One representative emoji per tab. */
export const CATEGORY_ICON: Record<EmojiCategory, string> = {
  people: "😀",
  nature: "🌳",
  food: "🍎",
  activity: "⚽",
  travel: "✈️",
  objects: "💡",
  symbols: "❤️",
};

export function emojisByCategory(cat: EmojiCategory): Emoji[] {
  return EMOJI.filter((e) => e.category === cat);
}

/* ─── The ":" inline trigger predicate ─────────────────────────
 *
 * A pure function so it can be tested exhaustively without a DOM.
 * Given the text BEFORE the caret in the current block, returns:
 *   { open: true,  query }   the popup should be visible with `query`
 *   { open: false, query: "" } otherwise
 *
 * Rules (intentionally strict — ":" is common in prose):
 *  - The ":" must be at the start of the block, or preceded by
 *    whitespace. "word:foo" never triggers ("10:30", "Note: hi").
 *  - Require at least ONE character typed after the ":".
 *  - The query accepts letters, digits, hyphen and underscore
 *    only; anything else (including a space) closes it.
 *  - Cap the query at 24 characters.
 */
export function shouldOpenEmojiTrigger(
  textBeforeCaret: string,
): { open: boolean; query: string } {
  const NO = { open: false, query: "" } as const;
  // Find the last ":" in the text before the caret.
  const colon = textBeforeCaret.lastIndexOf(":");
  if (colon < 0) return NO;
  // Anything after the colon becomes the query. Only letters/digits/-/_.
  const query = textBeforeCaret.slice(colon + 1);
  if (query.length === 0) return NO;
  if (query.length > 24) return NO;
  if (!/^[A-Za-z0-9_-]+$/.test(query)) return NO;
  // The ":" must be at start of block or preceded by whitespace.
  if (colon > 0) {
    const prev = textBeforeCaret[colon - 1];
    if (!/\s/.test(prev)) return NO;
  }
  return { open: true, query };
}
