/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VViewIdRouteImport } from './routes/v.$viewId'
import { Route as AAreaRouteImport } from './routes/a.$area'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VViewIdRoute = VViewIdRouteImport.update({
  id: '/v/$viewId',
  path: '/v/$viewId',
  getParentRoute: () => rootRouteImport,
} as any)
const AAreaRoute = AAreaRouteImport.update({
  id: '/a/$area',
  path: '/a/$area',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/a/$area': typeof AAreaRoute
  '/v/$viewId': typeof VViewIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/a/$area': typeof AAreaRoute
  '/v/$viewId': typeof VViewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/a/$area': typeof AAreaRoute
  '/v/$viewId': typeof VViewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/a/$area' | '/v/$viewId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/a/$area' | '/v/$viewId'
  id: '__root__' | '/' | '/login' | '/a/$area' | '/v/$viewId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AAreaRoute: typeof AAreaRoute
  VViewIdRoute: typeof VViewIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/$viewId': {
      id: '/v/$viewId'
      path: '/v/$viewId'
      fullPath: '/v/$viewId'
      preLoaderRoute: typeof VViewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a/$area': {
      id: '/a/$area'
      path: '/a/$area'
      fullPath: '/a/$area'
      preLoaderRoute: typeof AAreaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AAreaRoute: AAreaRoute,
  VViewIdRoute: VViewIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
