// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fzbsautaxfuqnjkchske.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6YnNhdXRheGZ1cW5qa2Noc2tlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQ5OTg3OTAsImV4cCI6MjEwMDU3NDc5MH0.RCsf1VPGHPBppVJiEO8NalXrz6U5jC6uQLlELVhDJI4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});